# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd9e14cc19c42cca1306064c2fe24e383c9d43267c108eae93da15ee51856c89ceab9883166d3cf091d843ec4504e60a4fee5fac3036e1a8775acb862012cdb5

test:
  secret_key_base: 4c0e2922988c16fabf1e19a3838b8a490df7e3b3fa0b3a3741685a87673c5d8d84aad0577087dd5a5739f81271b376d255b0584f8e6c9df29c0f5f9e02dc6255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
